### ISSUE TITLE
Fails to read some dictionary encoded vectors

### ISSUE THREAD

**Issue by TheNeuralBit** [graphistry/arrow#5] opened 2017-08-25 15:46 UTC
I'm having trouble reading some arrow files that we've generated with geomesa, and I think the problem comes down to dictionary encoded vectors, which we use heavily. Your vector loader just uses the field's layout directly (https://github.com/graphistry/arrow/blob/master/src/reader/vector.ts#L211), but for dictionary encoded fields it should actually replace the layout with the expected layout for an index.

We do this in our original implementation: 
https://github.com/apache/arrow/blob/master/js/src/arrow.ts#L496

and you can also see it in the java reader:
https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/file/ArrowReader.java#L169
https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/util/DictionaryUtility.java#L79

I think an argument could be made that the schema should contain the actual layout used for each field, including dictionary indexes, but that doesn't seem to be a requirement right now.

**Comment by TheNeuralBit** [comment] 2017-08-25 16:07
I'd be happy to write a PR for this if you want

I've started a fork that adds a couple of test files: https://github.com/TheNeuralBit/arrow-1/tree/dictionary/test/arrows/file
- dictionary2.arrow demonstrates exactly this issue. The file is read successfully but the data is corrupt since the vectors are loaded incorrectly.
- multi_dictionary.arrow has two dictionary-encoded vectors, and it actually throws an error when I try to read it. I think this may be a separate issue.

Both files were generated from json files using the java side of the integration tests in apache/arrow

**Comment by trxcllnt** [comment] 2017-08-25 17:16
@TheNeuralBit thanks for the test files, I'll check it out. Is this related to https://issues.apache.org/jira/browse/ARROW-1363?

**Comment by TheNeuralBit** [comment] 2017-08-25 17:29
Ah yep that looks like its referring to the same issue

**Comment by trxcllnt** [comment] 2017-08-25 17:41
@TheNeuralBit I'm debugging the `multi_dictionary` file right now, and I'm actually unclear on the intended behavior. This is the field metadata for the second Utf8 node in the dictionary batch:

```
field type: Utf8, name: Type, layout length: 3
node length: {"low":0,"high":3}
field 0 type: VALIDITY, buffer length: {"low":0,"high":0}
field 1 type: OFFSET, buffer length: {"low":6,"high":12}
field 2 type: DATA, buffer length: {"low":0,"high":212}
```

From everything I'd read before, we [use the `low`](https://github.com/graphistry/arrow/blob/master/src/reader/vector.ts#L209) half of any Long values, but here a number of the Longs have high values specified, and 0 lows. Is this expected, or possibly the reader is behind by one byte?

**Comment by TheNeuralBit** [comment] 2017-08-25 17:54
@trxcllnt yeah we definitely should only be using the low half of Longs right now

When I read this with our implementation there are actually two different dictionary batches - maybe you're trying to read the buffers for the second dictionary out of the first dictionary batch?

I see three buffers with lengths 1, 12, and 12

**Comment by trxcllnt** [comment] 2017-08-25 18:17
@TheNeuralBit from what I can tell, the first RecordBatch has a Struct node with a Utf8 child at index 1 named `"MMSI"` with id `"2581628073839966000"`, and another Utf8 child at index 2 named "Type" with id `"3678166276199606000"`. The second Utf8 child is reporting the values in my previous comment. I'm under the impression the reader should [recursively read the child fields](https://github.com/graphistry/arrow/blob/master/src/reader/dictionary.ts#L36) of any vectors in the dictionary batch. Is that right?

**Comment by trxcllnt** [comment] 2017-08-25 18:26
The batch reports `nodeLength()` of 1/`bufferLength()` of 3, and it's definitely possible for the reader to bail early if it reads nodes up to that value, but I'm still confused why the first dictionary batch defines a Struct vector but doesn't include node/buffers for all of its children?

**Comment by TheNeuralBit** [comment] 2017-08-25 18:34
@trxcllnt Oh that's definitely where our two implementations are diverging.

I don't think the first dictionary batch is actually defining that Struct anywhere, that's coming from the Schema. The two dictionary batches are just defining dictionaries for the Type and MMSI vectors, and don't really care about the hierarchy except for what's contained within Type and MMSI.

**Comment by TheNeuralBit** [comment] 2017-08-25 18:43
@trxcllnt Our implementation [iterates over the dictionary batches](https://github.com/apache/arrow/blob/master/js/src/arrow.ts#L196) and loads buffers into each dictionary from its corresponding DictionaryBatch

We do [recurse over child vectors](https://github.com/apache/arrow/blob/master/js/src/arrow.ts#L511) just like any other vector - but that's just fully loading the dictionary, not defining any new ones.

**Comment by trxcllnt** [comment] 2017-08-25 18:56
@TheNeuralBit ok, I think the bit I missed was [here](https://github.com/apache/arrow/blob/master/js/src/arrow.ts#L329). If I'm reading that right, you recursively create all the vectors with Dictionary encodings defined in the schema, but the data for each vector is only in the record batch whose `id` matches the vector's encoding `id`? If that's accurate, this should be a relatively easy fix. Testing that hypothesis out now.

**Comment by trxcllnt** [comment] 2017-08-25 19:05
@TheNeuralBit for reference, what's encoded in the `multi_dictionary` arrow file? After this change I'm reading:

```js
name: "struct"
type: "Struct_"
length: 2
0: ["a0fb47f9-f8fb-4403-a64a-786d7611f8ef", null, null, null, Float32Array(0)]
1: ["50fb46f4-fefa-42c1-919c-0121974cdd00", "12345", null, null, Float32Array(0)]
```

**Comment by TheNeuralBit** [comment] 2017-08-25 19:07
Hm that looks like it has the same problem that I was seeing for the `dictionary2` file. The data should be:
```
a0fb47f9-f8fb-4403-a64a-786d7611f8ef,12345,Airbus,1502880750,32.45663833618164,1.8712350130081177
50fb46f4-fefa-42c1-919c-0121974cdd00,67890,Boeing,1502880750,38.766666412353516,-4.181231498718262
```

**Comment by TheNeuralBit** [comment] 2017-08-25 19:10
@trxcllnt I think in both cases too many buffers are being allocated to the index vectors, since the layout in the schema corresponds to the dictionary, and not the index

**Comment by trxcllnt** [comment] 2017-08-25 19:52
@TheNeuralBit yep, hard-coding dictionary index's layout fixes the problem. edit: disregard previous question, I think I can work through this

**Comment by trxcllnt** [comment] 2017-08-25 20:16
@TheNeuralBit ok, with a bit of hacking I think I've got it working. Will add these files to the tests and push a fix shortly. Thanks for helping me work through this!

**Comment by trxcllnt** [comment] 2017-08-25 20:18
@TheNeuralBit is the `dictionary2` file supposed to have the `12345` and `67890` values too?

**Comment by TheNeuralBit** [comment] 2017-08-25 20:20
@trxcllnt no problem glad to help! no the dictionary2 file should be missing that column - I took it out in that file since it looked like there were two different issues going on

**Comment by trxcllnt** [comment] 2017-08-25 20:30
@TheNeuralBit ok great, that's what I'm seeing too. It looks like this change breaks most all the other unit tests, so it'll take a bit to figure out how to fix all those now.

**Comment by TheNeuralBit** [comment] 2017-08-25 20:34
@trxcllnt oh no! FWIW I noticed that [this line](https://github.com/graphistry/arrow/blob/master/src/reader/vector.ts#L167) was actually making the original dictionary.arrow file work correctly, and may be breaking it now

**Comment by trxcllnt** [comment] 2017-08-25 21:57
@TheNeuralBit oh wild yeah I was wondering why there was that mismatch! I've pushed a fix in https://github.com/graphistry/arrow/commit/b33e37104600c43310f36a60724ef190c5cf7e29, if you'd kindly validate [this assumption](https://github.com/graphistry/arrow/commit/b33e37104600c43310f36a60724ef190c5cf7e29#diff-f29887599367fca8aa79cfe1735aa003R37) is accurate, I can publish a new version to npm asap

**Comment by TheNeuralBit** [comment] 2017-08-25 22:29
Looks good to me! :+1:

**Closed as completed** 2017-09-02 05:33 UTC
